apps/avon/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
 	url(r'^$',IndexView.as_view(),name='index'),
 	url(r'^ajax-create$',campaing_create,name='create'),
    url(r'^update/(?P<pk>\d+)$',campaing_update,name='update'),
    url(r'^delete/(?P<pk>\d+)$',campaing_delete,name='delete'),
    url(r'^ajax-list/$',ajax_list,name='ajax-list'),


    url(r'^article-create$',article_create,name='create_article'),
    url(r'^delete/article/(?P<id_art>\d+)$',article_delete,name='delete_article'),
    url(r'^detail/(?P<pk>\d+)$',campaing_detail,name='detail'),

    url(r'^detail_customer/$', DetailCustomer.as_view(), name='detail_customer'),
    url(r'^detail_customer/result/$', DetailCustomerResult.as_view(), name='result_customer'),
    url(r'^update/customer/(?P<id_customer>\d+)$', CustomerUpdate, name='update_customer'),
    url(r'^customer-create$',create_customer,name='create_customer'),

    url(r'^customer/list$',ListCustomers.as_view(),name='list_customer'),




]

avon_easy/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.avon.urls', namespace='avon')),
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/avon/models.py
from django.db import models

# Create your models here.

class Campaing(models.Model):
	name = models.CharField(max_length=50)
	campaing_num=models.PositiveIntegerField(default=0)
	deperture_date = models.DateField(null=True)
	arrival_date = models.DateField(null=True)
	def __str__(self):
		return self.name




class Customer(models.Model):
	name = models.CharField(max_length=50)
	debt = models.PositiveIntegerField(default=0,blank=True)
	class Meta:
		ordering=['debt']
	def __str__(self):
		return self.name

class Article(models.Model):
	CATEGORY_CHOICES=(
		('PYC','Perfumería y cosméticos'),
		('RYH','Ropa y del hogar'),
	)
	campaing=models.ForeignKey(Campaing,on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	price = models.PositiveIntegerField(default=0)
	category = models.CharField(max_length=5,choices=CATEGORY_CHOICES)
	buyer = models.ManyToManyField(Customer)

	class Meta:
		ordering=['name']


	def get_percent(self):
		return 30 if category == 'PYC' else 20
	def __str__(self):
		return self.name

apps/avon/forms.py
from django import forms
from .models import Campaing,Article,Customer
from django.conf import settings




class UpdateCustomer(forms.ModelForm):
	def __init__(self,*args,**kwargs):
		super(UpdateCustomer,self).__init__(*args,**kwargs)
		for i in self.fields:
			self.fields[i].widget.attrs['class']='form__field'

	class Meta:
		model=Customer
		exclude=['name']
		labels={'debt':'Cuenta'}


class CustomerForm(forms.ModelForm):
	def __init__(self,*args,**kwargs):
		super(CustomerForm,self).__init__(*args,**kwargs)
		for i in self.fields:
			self.fields[i].widget.attrs['class']='form__field'
			self.fields[i].widget.attrs['placeholder']=self.fields[i].label

	class Meta:
		fields='__all__'
		labels={'name':'Nombre','debt':'Deuda'}
		model=Customer


class DateInput(forms.DateInput):
	input_type='date'
	input_formats=settings.DATE_INPUT_FORMATS

class CampaingUpdateForm(forms.ModelForm):
	def __init__(self,*args,**kwargs):
		super(CampaingUpdateForm,self).__init__(*args,**kwargs)
		for i in self.fields:
			self.fields[i].widget.attrs['class']='form__field'
	class Meta:
		model=Campaing
		fields='__all__'

		labels={
			'name':'Nombre',
			'campaing_num':'Numero de camapaña',
			'deperture_date':'Fecha de salida',
			'arrival_date':'Fecha de llegada',
		}

class CampaingForm(forms.ModelForm):
	def __init__(self,*args,**kwargs):
		super(CampaingForm,self).__init__(*args,**kwargs)
		for i in self.fields:
			self.fields[i].widget.attrs['class']='form__field'
	class Meta:
		model=Campaing
		fields='__all__'

		widgets={
			'deperture_date':DateInput(),
			'arrival_date':DateInput(),
		}

		labels={
			'name':'Nombre',
			'campaing_num':'Numero de camapaña',
			'deperture_date':'Fecha de salida',
			'arrival_date':'Fecha de llegada',

		}

class ArticleForm(forms.ModelForm):
	def __init__(self,*args,**kwargs):
		super(ArticleForm,self).__init__(*args,**kwargs)
		for i in self.fields:
			self.fields[i].widget.attrs['class']= 'form__field' if not i == 'price' else 'form__field form__field--int'


	class Meta:
		model=Article
		exclude=['campaing']
		labels={
			'name':'Nombre',
			'price':'Precio',
			'category':'Categoría',
			'buyer':'Comprador',
		}

apps/avon/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import TemplateView,ListView,DeleteView,ListView
from .models import *
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.template.loader import render_to_string
from .forms import *
# Create your views here.



class IndexView(ListView):
	template_name='avon/index.html'

	def get_queryset(self):
		return Campaing.objects.all().order_by('-campaing_num')


class ListCustomers(ListView):
	template_name='avon/customer_list.html'

	def get_queryset(self):
		return Customer.objects.all().order_by('-debt')

class DetailCustomer(TemplateView):
	template_name='avon/detail_customer.html'

	def get(self,request):
		context={'object_list':Customer.objects.all()}
		return render(request,self.template_name,context)

class DetailCustomerResult(TemplateView):

	def get(self,request,*args,**kwargs):
		data=dict()
		id_customer=request.GET['id']
		request.session['id_customer']=id_customer
		customer=Customer.objects.get(pk=id_customer)
		articles=Article.objects.filter(buyer=customer)
		total=0
		for a in articles:
			total+=a.price
		context={
			'object_list':articles,
			'debt':customer.debt,
			'total':total,
			'is_owed':(True if customer.debt > 0 else False),
		}
		print('IS_OWED::::{}'.format(context['is_owed']))
		data['html_result']=render_to_string('avon/partial_html_result.html',context)
		return JsonResponse(data)


def CustomerUpdate(request,id_customer):
	instance=Customer.objects.get(pk=id_customer)
	data=dict()
	if request.method=='POST':
		form=UpdateCustomer(request.POST,instance=instance)
		form.save()
		data['form_is_valid']=True
		customer=Customer.objects.get(pk=id_customer)
		articles=Article.objects.filter(buyer=customer)
		total=0
		for a in articles:
			total+=a.price
		context={
			'object_list':articles,
			'debt':customer.debt,
			'total':total,
			'is_owed':(True if customer.debt > 0 else False),
		}
		data['html_list']=render_to_string('avon/partial_html_result.html',context)
	else:
		form=UpdateCustomer(instance=instance)
		data['form_is_valid']=False
	context={'form':form}
	data['html_form']=render_to_string('avon/partial_customer_form.html',context,request=request)
	return JsonResponse(data)


def save_form(request,form,template_name,template_list,Object,folder):
	data=dict()
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			data['form_is_valid']=True
			campaings=Object.objects.all()
			data['html_list']=render_to_string('avon/{}.html'.format(template_list),{'object_list':campaings})
		else:
			data['form_is_valid']=False
	context={'form':form}
	data['html_form']=render_to_string('avon/{1}/{0}.html'.format(template_name,folder),context,request=request)
	return JsonResponse(data)

def save_article_form(request,form,template_name,template_list,Object,folder):
	data=dict()
	if request.method == 'POST':
		if form.is_valid():
			article=form.save(commit=False)
			campaing=Campaing.objects.get(pk=request.session['id'])
			article.campaing=campaing
			article.save()
			##SAVE MANY TO MANY
			form.save_m2m()
			customers=list(str(value) for value in article.buyer.all())
			addDebt(customers,article.price)
			data['form_is_valid']=True
			object_list=Object.objects.filter(campaing=campaing)
			data['html_list']=render_to_string('avon/{}.html'.format(template_list),{'object_list':object_list})
		else:
			data['form_is_valid']=False
	context={'form':form}
	data['html_form']=render_to_string('avon/{1}/{0}.html'.format(template_name,folder),context,request=request)
	return JsonResponse(data)


def addDebt(customers,price):
	for customer in customers:
		c=Customer.objects.get(name=customer)
		c.debt+=price
		c.save()

def delete_object(request,obj,Object,template_list,template_delete,op):
	data=dict()
	if request.method=='POST':
		obj.delete()
		data['form_is_valid']=True
		objects=Object.objects.all() if op == 1 else Object.objects.filter(campaing=Campaing.objects.get(pk=request.session['id']))
		data['html_list']=render_to_string('avon/{}.html'.format(template_list),{'object_list': objects})
	else:
		context={'object':obj}
		data['html_form']=render_to_string('avon/delete/{}.html'.format(template_delete),context,request=request)
	return JsonResponse(data)

def campaing_delete(request,pk):
	campaing=get_object_or_404(Campaing,pk=pk)
	return delete_object(request,campaing,Campaing,'partial_list','partial_campaing_delete',1)



def campaing_create(request):
	if request.method =='POST':
		form=CampaingForm(request.POST)
	else:
		form=CampaingForm()
	return save_form(request,form,'partial_campaing_create','partial_list',Campaing,'create')


def campaing_update(request,pk):
	campaing=Campaing.objects.get(pk=pk)
	if request.method=='POST':
		form=CampaingUpdateForm(request.POST,instance=campaing)
	else:
		form=CampaingUpdateForm(instance=campaing)
	return save_form(request,form,'partial_campaing_update','partial_list',Campaing,'update')

#AJAX TEST
def ajax_list(request):
	return render(request,'avon/ajax_test.html')



def campaing_detail(request,pk):
	campaing=get_object_or_404(Campaing,pk=pk)
	request.session['id']=pk
	articles=Article.objects.filter(campaing=campaing).order_by('-price')
	return render(request,'avon/campaing_detail.html',{"object_list":articles})

def article_create(request):
	if request.method=='POST':
		form=ArticleForm(request.POST)
	else:
		form=ArticleForm()
	return save_article_form(request,form,'partial_article_create','partial_article_list',Article,'create')

def article_delete(request,id_art):
	article=get_object_or_404(Article,pk=id_art)
	return delete_object(request,article,Article,'partial_article_list','partial_article_delete',2)


def create_customer(request):
	data=dict()
	if request.method=='POST':
		form=CustomerForm(request.POST)
		form.save()
		data['form_is_valid']=True
		context={'object_list':Customer.objects.all()}
		data['options']=render_to_string('avon/partial_options.html',context)

	else:
		data['form_is_valid']=False
		form=CustomerForm()
	data['html_form']=render_to_string('avon/create/partial_customer_form_.html',{'form':form},request=request)
	return JsonResponse(data)

templates/avon/ajax_test.html
{% extends '../base.html' %}
{% block title %}Test AJAX{% endblock title %}
{% block content %}

	<header class="header">
		<h1>DEMO PRUEBAS</h1>
	</header>
	<aside class="aside">
		{% include "avon/menu.html" %}
	</aside>
	<main class="main">
			<h1>{{num}}</h1>
	</main>

	<div class="modal__cover" id="modal_content">
		<div class="modal">

		</div>
	</div>




	<!-- 	<button type="button" class="list-js" data-url='{% url 'avon:ajax-list' %}'>Listar</button>
	<div class="modal__cover">
		<div class="modal">
		</div>
	</div> -->




{% endblock content %}

templates/avon/campaing_detail.html
{% extends '../base.html' %}
{% block title %}Detail{% endblock title %}


{% block content %}
  <header class="header">
      <h1>Detalle</h1>
  </header>

  <aside class="aside">
    {% include 'avon/menu.html' %}
  </aside>

  <main class="main">
      <section  class="container">
        <button class="js-ajax button" type="button" data-url="{% url  'avon:create_article' %}" value="{{pk}}" ><i class="icon-plus"></i>AGREGAR ARTICULO</button>
        <table class="table" id="table">
            <thead>
                <tr>
                  <th>ARTICULO</th>
                  <th>PRECIO</th>
                  <th>CATEGORÍA</th>
                  <th>COMPRADOR</th>
                  <th>----</th>
                </tr>
            </thead>
            <tbody id="list">
                {% include 'avon/partial_article_list.html' %}
            </tbody>

        </table>
      </section>

      <div class="modal__cover" id="modal_content">
        <div class="modal">

        </div>
      </div>
  </main>


{% endblock content %}

templates/avon/customer_list.html
{% extends '../base.html' %}
{% block title %}Lista de clientes{% endblock title %}


{% block content %}
  <header class="header">
      <h1>Lista de clientes</h1>
  </header>
  <aside class="aside">
    {% include 'avon/menu.html' %}
  </aside>

  <main class="main">
    <section class="container">
        <table class="table">
            <thead>
              <th>Nombre</th>
              <th>Deuda</th>
              <th>---</th>
            </thead>
            <tbody>
              {% for x in object_list  %}
                  <tr>
                    <td>{{x}}</td>
                    <td>{{x.debt}}</td>
                    <td><button type="button" class="table__button"> <i class="icon-bin"></i> Eliminar</button>
</td>
                  </tr>
              {% endfor %}

            </tbody>
        </table>
    </section>
  </main>
{% endblock content %}

templates/avon/detail_customer.html
{% extends '../base.html' %}

{% block title %}AVON{% endblock title %}

{% block content %}
  <header class="header">
    <h1>DETALLE DE CLIENTES</h1>
    <!--<form  action="" method="GET" class="form--search">

      <input id="search" placeholder="Busque un cliente" type="search" name="search" value="" class="search__input">
      <button class="search__submit" type="submit" ><i class="icon-search"></i></button>
    </form>-->
  </header>

  <aside class="aside">
    {% include 'avon/menu.html' %}
  </aside>

  <main class="main">
    <section class="container">
      <div class="container__flex">
        <select class="select">
          {% include 'avon/partial_options.html' %}
        </select>
        <div class="btn">
        </div>
        <!--<button type="button" id="button_debt" class="js-ajax button" data-url="{% url  'avon:update_customer' 1 %}">EDITAR CUENTA</button>-->

      </div>
      <div id='list'>
          
      </div>
      <div class="modal__cover" id="modal_content">
        <div class="modal">

        </div>
      </div>

    </section>
  </main>
{% endblock content %}

templates/avon/index.html
{% extends '../base.html' %}
{% block title %}Home{% endblock title %}


{% block content %}
	<header class="header">
		<h1>AVON</h1>
	</header>
	<aside class="aside">
		{% include 'avon/menu.html' %}
	</aside>


	<main class="main" id="main">
			{% load static %}
			{% if object_list %}
				<section class="container">
					<button class="js-ajax button" type="button" data-url="{% url 'avon:create'%}"><i class="icon-plus"></i>Agregar una campaña</button>

					<table class="table" id="table">
						<thead>
							<tr>
								<th>Nombre</th>
								<th>Num. de Campaña</th>
								<th>Fecha de salida</th>
								<th>Fecha de llegada</th>
								<th>---</th>
							</tr>
						</thead>
						<tbody id="list">
							{% include "avon/partial_list.html" %}
						</tbody>
					</table>
				</section>
			{% else %}
				<section class="container">
					<button class="js-ajax button button--add" type="button" data-url="{% url 'avon:create'%}"><i class="icon-plus"></i>Agregar una campaña</button>
					<table class="table" id="table">
						<thead>
							<tr>
								<th>Nombre</th>
								<th>Num. de Campaña</th>
								<th>Fecha de salida</th>
								<th>Fecha de llegada</th>
								<th>---</th>
							</tr>
						</thead>
						<tbody id="list">
							{% include "avon/partial_list.html" %}
						</tbody>
					</table>

				</section>
			{% endif %}

	<div class="modal__cover" id="modal_content">
		<div class="modal">

		</div>
	</div>
	</main>
	<script src="http://localhost:35729/livereload.js"></script>

{% endblock content %}

templates/avon/menu.html
<nav class="menu">
		<ul>
			<li class="menu__li"><a class="menu__a" href="{% url 'avon:index' %}">
				<i class="icon icon-home"></i></a>
			</li>
			<li class="menu__li"><a class="menu__a" href="{% url  'avon:detail_customer' %}">
				<i class="icon icon-address-book"></i></a>
			</li>
			<li class="menu__li" ><button class="js-ajax menu__btn" data-url="{% url  'avon:create_customer' %}" ><i class="icon icon-user-plus"></i></button></li>
			<li class="menu__li"><a class="menu__a" href="{% url  'avon:list_customer' %}">
				<i class="icon icon-trophy"></i></a>
			</li>
		</ul>
</nav>

templates/avon/partial_article_list.html
{% for x in object_list  %}
    <tr>
      <td>{{x}}</td>
      <td>${{x.price}}</td>
      <td>{{x.category}}</td>
      <td>
        {% for i in x.buyer.all  %}
            <p>{{i}}</p>
        {% endfor %}

      </td>
      <td>
        <button type="button" class="js-delete-campaing table__button delete" data-url="{% url 'avon:delete_article' x.pk %}"> <i class="icon-bin"></i> Eliminar</button>
      </td>
    </tr>
{% empty %}
<tr>
  <td colspan="5">NO HAY ARTICULOS</td>
</tr>
{% endfor %}

templates/avon/partial_delete.html
<h1 class="title">Desea borrar {{object}}? </h1>
	<form method="POST" class="form"> {% csrf_token %}
		<button type="submit" class="form__submit">Si, eliminar</button>
		<a href="{% url 'avon:index' %}" class="button button--cancel">Cancelar</a>
	</form>

templates/avon/partial_html_result.html
<table class="table table--result">
  <thead>
    <tr>
      <th>Articulo</th>
      <th>Precio</th>
    </tr>
  </thead>

  <tbody>
    {% for x in object_list  %}
        <tr>
          <td>{{x.name}}</td>
          <td>${{x.price}}</td>
        </tr>
    {% empty %}
        <tr>
          <td colspan="2">NO TIENE ARTICULOS</td>
        </tr>
    {% endfor %}

  </tbody>

  {% if is_owed %}
    <tfoot class="table__total">
      <tr >
        <td>TOTAL</td>
        <td colspan="2">${{total}}</td>
      </tr>
      <tr >
        <td>RESTANTE</td>
        <td colspan="2">${{debt}}</td>
      </tr>
    </tfoot>
  {% endif %}


</table>

templates/avon/partial_list.html
{% for x in object_list  %}
	<tr>
		<td>{{x.name}}</td>
		<td>{{x.campaing_num}}</td>
		<td>{{x.deperture_date}}</td>
		<td>{{x.arrival_date}}</td>
		<td>
			<a href="{% url  'avon:detail' x.pk %}" class="table__button table__button--a"><i class="icon-folder-plus"></i>ARTICULOS</a>
			<button type="button" class="js-update-campaing table__button" data-url="{% url  "avon:update" x.pk %}" > <i class="icon-edit"></i>Editar</button>
			<button type="button" class="js-delete-campaing table__button" data-url="{% url "avon:delete" x.pk %}"> <i class="icon-bin"></i> Eliminar</button>
		</td>
	</tr>
{% empty %}
	<tr>
		<td colspan="5">NO HAY NINGUNA CAMPAÑA</td>
	</tr>
{% endfor %}

templates/avon/partial_options.html
<option>Eliga un cliente...</option>
{% for x in object_list  %}
    <option value="{{x.pk}}">{{x.name}}</option>
{% endfor %}